package ppA.entity;
// Generated 09-oct-2016 21:14:52 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Abonos generated by hbm2java
 */
public class Abonos implements java.io.Serializable {

    private int id;
    private Clientes clientes;
    private Reservaciones reservaciones;
    private BigDecimal abono;
    private Date fechaAbono;
    private int idUsuario;

    public Abonos() {
    }

    public Abonos(int id, Clientes clientes, Reservaciones reservaciones, BigDecimal abono, Date fechaAbono, int idUsuario) {
	this.id = id;
	this.clientes = clientes;
	this.reservaciones = reservaciones;
	this.abono = abono;
	this.fechaAbono = fechaAbono;
	this.idUsuario = idUsuario;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public Clientes getClientes() {
	return this.clientes;
    }

    public void setClientes(Clientes clientes) {
	this.clientes = clientes;
    }

    public Reservaciones getReservaciones() {
	return this.reservaciones;
    }

    public void setReservaciones(Reservaciones reservaciones) {
	this.reservaciones = reservaciones;
    }

    public BigDecimal getAbono() {
	return this.abono;
    }

    public void setAbono(BigDecimal abono) {
	this.abono = abono;
    }

    public Date getFechaAbono() {
	return this.fechaAbono == null ? new Date() : this.fechaAbono;
    }

    public void setFechaAbono(Date fechaAbono) {
	this.fechaAbono = fechaAbono;
    }

    public int getIdUsuario() {
	return this.idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
	this.idUsuario = idUsuario;
    }

}
