package ppA.entity;
// Generated 09-oct-2016 21:14:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriasMenus generated by hbm2java
 */
public class CategoriasMenus  implements java.io.Serializable {


     private int id;
     private String categoriaMenu;
     private String descripcion;
     private Set menuses = new HashSet(0);

    public CategoriasMenus() {
    }

	
    public CategoriasMenus(int id, String categoriaMenu, String descripcion) {
        this.id = id;
        this.categoriaMenu = categoriaMenu;
        this.descripcion = descripcion;
    }
    public CategoriasMenus(int id, String categoriaMenu, String descripcion, Set menuses) {
       this.id = id;
       this.categoriaMenu = categoriaMenu;
       this.descripcion = descripcion;
       this.menuses = menuses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCategoriaMenu() {
        return this.categoriaMenu;
    }
    
    public void setCategoriaMenu(String categoriaMenu) {
        this.categoriaMenu = categoriaMenu;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getMenuses() {
        return this.menuses;
    }
    
    public void setMenuses(Set menuses) {
        this.menuses = menuses;
    }




}


