package ppA.entity;
// Generated 09-oct-2016 21:14:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellido;
     private String telefono;
     private String correo;
     private String dui;
     private String nit;
     private String comprobanteIva;
     private String descripcion;
     private Set abonoses = new HashSet(0);
     private Set reservacioneses = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(int id, String nombre, String apellido, String telefono, String correo, String dui, String nit, String comprobanteIva, String descripcion) {
        this.id = id;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.correo = correo;
        this.dui = dui;
        this.nit = nit;
        this.comprobanteIva = comprobanteIva;
        this.descripcion = descripcion;
    }
    public Clientes(int id, String nombre, String apellido, String telefono, String correo, String dui, String nit, String comprobanteIva, String descripcion, Set abonoses, Set reservacioneses) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.correo = correo;
       this.dui = dui;
       this.nit = nit;
       this.comprobanteIva = comprobanteIva;
       this.descripcion = descripcion;
       this.abonoses = abonoses;
       this.reservacioneses = reservacioneses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getComprobanteIva() {
        return this.comprobanteIva;
    }
    
    public void setComprobanteIva(String comprobanteIva) {
        this.comprobanteIva = comprobanteIva;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getAbonoses() {
        return this.abonoses;
    }
    
    public void setAbonoses(Set abonoses) {
        this.abonoses = abonoses;
    }
    public Set getReservacioneses() {
        return this.reservacioneses;
    }
    
    public void setReservacioneses(Set reservacioneses) {
        this.reservacioneses = reservacioneses;
    }




}


