package ppA.entity;
// Generated 09-oct-2016 21:14:52 by Hibernate Tools 4.3.1



/**
 * DetallesMenus generated by hbm2java
 */
public class DetallesMenus  implements java.io.Serializable {


     private int id;
     private Menus menus;
     private Reservaciones reservaciones;
     private int cantidad;
     private String comentarios;
     private double precio;

    public DetallesMenus() {
    }

    public DetallesMenus(int id, Menus menus, Reservaciones reservaciones, int cantidad, String comentarios, double precio) {
       this.id = id;
       this.menus = menus;
       this.reservaciones = reservaciones;
       this.cantidad = cantidad;
       this.comentarios = comentarios;
       this.precio = precio;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Menus getMenus() {
        return this.menus;
    }
    
    public void setMenus(Menus menus) {
        this.menus = menus;
    }
    public Reservaciones getReservaciones() {
        return this.reservaciones;
    }
    
    public void setReservaciones(Reservaciones reservaciones) {
        this.reservaciones = reservaciones;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }




}


