package ppA.entity;
// Generated 11-oct-2016 21:57:08 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Estados generated by hbm2java
 */
public class Estados implements java.io.Serializable {

    private int id;
    private String estado;
    private String descripcion;
    private String color;
    private Set reservacioneses = new HashSet(0);
    private Set reservacioneses_1 = new HashSet(0);

    public Estados() {
    }

    public Estados(int id, String estado, String descripcion, String color) {
        this.id = id;
        this.estado = estado;
        this.descripcion = descripcion;
        this.color = color;
    }

    public Estados(int id, String estado, String descripcion, String color, Set reservacioneses, Set reservacioneses_1) {
        this.id = id;
        this.estado = estado;
        this.descripcion = descripcion;
        this.color = color;
        this.reservacioneses = reservacioneses;
        this.reservacioneses_1 = reservacioneses_1;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Set getReservacioneses() {
        return this.reservacioneses;
    }

    public void setReservacioneses(Set reservacioneses) {
        this.reservacioneses = reservacioneses;
    }

    public Set getReservacioneses_1() {
        return this.reservacioneses_1;
    }

    public void setReservacioneses_1(Set reservacioneses_1) {
        this.reservacioneses_1 = reservacioneses_1;
    }

}
