package ppA.entity;
// Generated 02-oct-2016 10:52:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estados generated by hbm2java
 */
public class Estados  implements java.io.Serializable {


     private int id;
     private String estado;
     private String descripcion;
     private Set reservacioneses = new HashSet(0);
     private Set reservacioneses_1 = new HashSet(0);

    public Estados() {
    }

	
    public Estados(int id, String estado, String descripcion) {
        this.id = id;
        this.estado = estado;
        this.descripcion = descripcion;
    }
    public Estados(int id, String estado, String descripcion, Set reservacioneses, Set reservacioneses_1) {
       this.id = id;
       this.estado = estado;
       this.descripcion = descripcion;
       this.reservacioneses = reservacioneses;
       this.reservacioneses_1 = reservacioneses_1;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getReservacioneses() {
        return this.reservacioneses;
    }
    
    public void setReservacioneses(Set reservacioneses) {
        this.reservacioneses = reservacioneses;
    }
    public Set getReservacioneses_1() {
        return this.reservacioneses_1;
    }
    
    public void setReservacioneses_1(Set reservacioneses_1) {
        this.reservacioneses_1 = reservacioneses_1;
    }




}


