package ppA.entity;
// Generated 09-oct-2016 21:14:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Menus generated by hbm2java
 */
public class Menus  implements java.io.Serializable {


     private int id;
     private CategoriasMenus categoriasMenus;
     private String menu;
     private BigDecimal precio;
     private String descripcion;
     private Set detallesMenuses = new HashSet(0);

    public Menus() {
    }

	
    public Menus(int id, CategoriasMenus categoriasMenus, String menu, String descripcion) {
        this.id = id;
        this.categoriasMenus = categoriasMenus;
        this.menu = menu;
        this.descripcion = descripcion;
    }
    public Menus(int id, CategoriasMenus categoriasMenus, String menu, BigDecimal precio, String descripcion, Set detallesMenuses) {
       this.id = id;
       this.categoriasMenus = categoriasMenus;
       this.menu = menu;
       this.precio = precio;
       this.descripcion = descripcion;
       this.detallesMenuses = detallesMenuses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CategoriasMenus getCategoriasMenus() {
        return this.categoriasMenus;
    }
    
    public void setCategoriasMenus(CategoriasMenus categoriasMenus) {
        this.categoriasMenus = categoriasMenus;
    }
    public String getMenu() {
        return this.menu;
    }
    
    public void setMenu(String menu) {
        this.menu = menu;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDetallesMenuses() {
        return this.detallesMenuses;
    }
    
    public void setDetallesMenuses(Set detallesMenuses) {
        this.detallesMenuses = detallesMenuses;
    }




}


