package ppA.entity;
// Generated 11-oct-2016 21:57:08 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * Opciones generated by hbm2java
 */
public class Opciones implements java.io.Serializable {

    private int id;
    private String opcion;
    private BigDecimal orden;
    private Integer padre;
    private String accion;
    private String descripcion;

    public Opciones() {
    }

    public Opciones(int id, String opcion, String accion, String descripcion) {
	this.id = id;
	this.opcion = opcion;
	this.accion = accion;
	this.descripcion = descripcion;
    }

    public Opciones(int id, String opcion, BigDecimal orden, Integer padre, String accion, String descripcion) {
	this.id = id;
	this.opcion = opcion;
	this.orden = orden;
	this.padre = padre;
	this.accion = accion;
	this.descripcion = descripcion;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public String getOpcion() {
	return this.opcion;
    }

    public void setOpcion(String opcion) {
	this.opcion = opcion;
    }

    public BigDecimal getOrden() {
	return this.orden;
    }

    public void setOrden(BigDecimal orden) {
	this.orden = orden;
    }

    public Integer getPadre() {
	return this.padre;
    }

    public void setPadre(Integer padre) {
	this.padre = padre;
    }

    public String getAccion() {
	return this.accion;
    }

    public void setAccion(String accion) {
	this.accion = accion;
    }

    public String getDescripcion() {
	return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
	this.descripcion = descripcion;
    }

}
