package ppA.entity;
// Generated 18-sep-2016 22:35:39 by Hibernate Tools 4.3.1



/**
 * Sucursales generated by hbm2java
 */
public class Sucursales  implements java.io.Serializable {


     private int id;
     private String sucursal;
     private int nacional;
     private String direccion;
     private String telefono;
     private Reservaciones reservaciones;

    public Sucursales() {
    }

	
    public Sucursales(int id, String sucursal, int nacional, String direccion, String telefono) {
        this.id = id;
        this.sucursal = sucursal;
        this.nacional = nacional;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Sucursales(int id, String sucursal, int nacional, String direccion, String telefono, Reservaciones reservaciones) {
       this.id = id;
       this.sucursal = sucursal;
       this.nacional = nacional;
       this.direccion = direccion;
       this.telefono = telefono;
       this.reservaciones = reservaciones;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }
    public int getNacional() {
        return this.nacional;
    }
    
    public void setNacional(int nacional) {
        this.nacional = nacional;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Reservaciones getReservaciones() {
        return this.reservaciones;
    }
    
    public void setReservaciones(Reservaciones reservaciones) {
        this.reservaciones = reservaciones;
    }




}


