package ppA.entity;
// Generated 02-oct-2016 10:52:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursales generated by hbm2java
 */
public class Sucursales  implements java.io.Serializable {


     private int id;
     private String sucursal;
     private int nacional;
     private String direccion;
     private String telefono;
     private Set reservacioneses = new HashSet(0);
     private Set reservacioneses_1 = new HashSet(0);

    public Sucursales() {
    }

	
    public Sucursales(int id, String sucursal, int nacional, String direccion, String telefono) {
        this.id = id;
        this.sucursal = sucursal;
        this.nacional = nacional;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Sucursales(int id, String sucursal, int nacional, String direccion, String telefono, Set reservacioneses, Set reservacioneses_1) {
       this.id = id;
       this.sucursal = sucursal;
       this.nacional = nacional;
       this.direccion = direccion;
       this.telefono = telefono;
       this.reservacioneses = reservacioneses;
       this.reservacioneses_1 = reservacioneses_1;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }
    public int getNacional() {
        return this.nacional;
    }
    
    public void setNacional(int nacional) {
        this.nacional = nacional;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getReservacioneses() {
        return this.reservacioneses;
    }
    
    public void setReservacioneses(Set reservacioneses) {
        this.reservacioneses = reservacioneses;
    }
    public Set getReservacioneses_1() {
        return this.reservacioneses_1;
    }
    
    public void setReservacioneses_1(Set reservacioneses_1) {
        this.reservacioneses_1 = reservacioneses_1;
    }




}


