package ppA.entity;
// Generated 09-oct-2016 21:14:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int id;
     private Roles roles;
     private String usuario;
     private String clave;
     private Set reservacioneses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int id, Roles roles, String usuario, String clave) {
        this.id = id;
        this.roles = roles;
        this.usuario = usuario;
        this.clave = clave;
    }
    public Usuarios(int id, Roles roles, String usuario, String clave, Set reservacioneses) {
       this.id = id;
       this.roles = roles;
       this.usuario = usuario;
       this.clave = clave;
       this.reservacioneses = reservacioneses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set getReservacioneses() {
        return this.reservacioneses;
    }
    
    public void setReservacioneses(Set reservacioneses) {
        this.reservacioneses = reservacioneses;
    }




}


