package ppA.entity;
// Generated 11-oct-2016 21:57:08 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

    private int id;
    private Roles roles;
    private String nombre;
    private String apellido;
    private String usuario;
    private String clave;
    private Set reservacioneses = new HashSet(0);
    private Set abonoses = new HashSet(0);
    private Set abonoses_1 = new HashSet(0);
    private Set reservacioneses_1 = new HashSet(0);

    public Usuarios() {
    }

    public Usuarios(int id, Roles roles, String nombre, String apellido, String usuario, String clave) {
	this.id = id;
	this.roles = roles;
	this.nombre = nombre;
	this.apellido = apellido;
	this.usuario = usuario;
	this.clave = clave;
    }

    public Usuarios(int id, Roles roles, String nombre, String apellido, String usuario, String clave, Set reservacioneses, Set abonoses, Set abonoses_1, Set reservacioneses_1) {
	this.id = id;
	this.roles = roles;
	this.nombre = nombre;
	this.apellido = apellido;
	this.usuario = usuario;
	this.clave = clave;
	this.reservacioneses = reservacioneses;
	this.abonoses = abonoses;
	this.abonoses_1 = abonoses_1;
	this.reservacioneses_1 = reservacioneses_1;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public Roles getRoles() {
	return this.roles;
    }

    public void setRoles(Roles roles) {
	this.roles = roles;
    }

    public String getNombre() {
	return this.nombre;
    }

    public void setNombre(String nombre) {
	this.nombre = nombre;
    }

    public String getApellido() {
	return this.apellido;
    }

    public void setApellido(String apellido) {
	this.apellido = apellido;
    }

    public String getUsuario() {
	return this.usuario;
    }

    public void setUsuario(String usuario) {
	this.usuario = usuario;
    }

    public String getClave() {
	return this.clave;
    }

    public void setClave(String clave) {
	this.clave = clave;
    }

    public Set getReservacioneses() {
	return this.reservacioneses;
    }

    public void setReservacioneses(Set reservacioneses) {
	this.reservacioneses = reservacioneses;
    }

    public Set getAbonoses() {
	return this.abonoses;
    }

    public void setAbonoses(Set abonoses) {
	this.abonoses = abonoses;
    }

    public Set getAbonoses_1() {
	return this.abonoses_1;
    }

    public void setAbonoses_1(Set abonoses_1) {
	this.abonoses_1 = abonoses_1;
    }

    public Set getReservacioneses_1() {
	return this.reservacioneses_1;
    }

    public void setReservacioneses_1(Set reservacioneses_1) {
	this.reservacioneses_1 = reservacioneses_1;
    }

}
