package ppA.entity;
// Generated 02-oct-2016 10:52:33 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int id;
     private Roles roles;
     private String usuario;
     private String clave;

    public Usuarios() {
    }

    public Usuarios(int id, Roles roles, String usuario, String clave) {
       this.id = id;
       this.roles = roles;
       this.usuario = usuario;
       this.clave = clave;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


